name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install dependencies and build ğŸ”§
        run: |
          npm install
          npm run build # The build command for your project

      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src # Change 'dist' to your project's build folder
